"""
DriveVitals Vehicle State

Represents the latest live state of a single vehicle.

This object is continuously updated as new telemetry
arrives from the analytics pipeline.
"""

from dataclasses import dataclass, field
from datetime import datetime


@dataclass
class VehicleState:

    # Vehicle identity
    vehicle_id: str

    status: str = "Offline"

    # Latest telemetry packet
    telemetry: dict = field(default_factory=dict)

    # Analytics results
    driver_behaviour: dict = field(default_factory=dict)

    vehicle_health: dict = field(default_factory=dict)

    fuel_efficiency: dict = field(default_factory=dict)

    trip_performance: dict = field(default_factory=dict)

    # Active alerts generated by Rule Engine
    alerts: list = field(default_factory=list)

    driver_ranking: dict = field(
        default_factory=lambda:{
            "driver_id": None,
            "vehicle_id": None,
            "score":100,
            "grade":"Excellent",
            "violations":0
        }
    )

    maintenance_queue: list = field(default_factory=list)
    # Last update timestamp
    last_updated: datetime | None = None