"""add_alert_canonical_fields

Revision ID: a7a996678ad6
Revises: d2f4b9a1c3e7
Create Date: 2026-08-13 17:51:18.473003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7a996678ad6'
down_revision: Union[str, Sequence[str], None] = 'd2f4b9a1c3e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('alerts', sa.Column('condition', sa.String(length=100), nullable=True))
    op.add_column('alerts', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('alerts', sa.Column('message', sa.Text(), nullable=True))
    op.add_column('alerts', sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('alerts', sa.Column('source', sa.String(length=20), nullable=False, server_default='alert_engine'))
    op.create_index(op.f('ix_alerts_category'), 'alerts', ['category'], unique=False)
    op.create_index(op.f('ix_alerts_condition'), 'alerts', ['condition'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_condition'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_category'), table_name='alerts')
    op.drop_column('alerts', 'source')
    op.drop_column('alerts', 'evidence')
    op.drop_column('alerts', 'message')
    op.drop_column('alerts', 'category')
    op.drop_column('alerts', 'condition')
    op.drop_column('alerts', 'acknowledged_at')
    # ### end Alembic commands ###
