"""
HealthReason model.

A single, presentation-ready reason for a degraded health condition,
tagged with the subsystem that produced it. Reasons are always derived
from the canonical vehicle health pipeline — never invented on the
frontend — so this model only exists to carry the meaning generated by
the subsystem analyzers to the dashboard and REST layers.

The reason contract now exposes structured semantic fields so the
frontend can render explainable health intelligence instead of raw
strings:

    code             stable machine-readable identifier
    title            human-readable headline
    severity         INFO | WARNING | CRITICAL
    summary          concise explanation of what was detected
    evidence         quantitative data supporting the assessment
    impact           operational consequence if unaddressed
    recommendation   suggested operator action

    SubsystemHealth.reasons
            ↓
         HealthReason(subsystem, reason, ...)
"""

from dataclasses import dataclass, field


@dataclass(frozen=True, slots=True)
class HealthReason:
    """
    Purpose:
        Carry one health reason plus the subsystem it belongs to,
        together with structured metadata that lets the frontend
        render explainable operational intelligence.
    Inputs:
        Produced by flatten_health_reasons from a HealthSnapshot.
    Outputs:
        Consumed by the dashboard payload and the persisted REST
        representation so the frontend can group and prioritise them.
    """

    subsystem: str
    reason: str
    code: str = ""
    title: str = ""
    severity: str = "warning"
    summary: str = ""
    evidence: dict[str, object] | None = None
    impact: str | None = None
    recommendation: str | None = None

    def to_dict(self) -> dict[str, object]:
        """JSON-friendly representation for persistence."""
        return {
            "subsystem": self.subsystem,
            "reason": self.reason,
            "code": self.code,
            "title": self.title,
            "severity": self.severity,
            "summary": self.summary,
            "evidence": self.evidence,
            "impact": self.impact,
            "recommendation": self.recommendation,
        }


__all__ = ["HealthReason"]
