"""
DriveVitals Driver Ranking Analyzer

Calculates a live driver safety score based on
rule violations generated by the Rule Engine.

The score ranges from 0–100 and is intended
for fleet manager comparison only.
"""


class DriverRankingAnalyzer:

    def __init__(self):
        self.active_violations = {}

        self.PENALTIES = {

        "overspeed": 15,

        "high_rpm": 8,

        "high_engine_load": 5,

        "high_fuel_consumption": 6,

        "excessive_idle": 2,
    }

    def analyze(self, packet, rule_results, current_score):
        score = current_score

        for rule in rule_results:

            event = rule["event"]

            # First time violation only
            if event not in self.active_violations:

                score -= self.PENALTIES.get(
                    event,
                    0
                )
                self.active_violations[event] = True

        score = max(score, 0)

        if score >= 90:

            grade = "Excellent"

        elif score >= 80:

            grade = "Good"

        elif score >= 70:

            grade = "Average"

        else:

            grade = "Needs Coaching"
        
        return {

           "driver_id": packet.driver_id,

           "vehicle_id": packet.vehicle_id,

           "score": max(score,0),

           "grade": grade,
        }

    