"""initial schema

Revision ID: e1d0ce255153
Revises: 
Create Date: 2026-07-14 14:46:59.812773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1d0ce255153'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fleets',
    sa.Column('fleet_id', sa.UUID(), nullable=False),
    sa.Column('fleet_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('fleet_id'),
    sa.UniqueConstraint('fleet_name')
    )
    op.create_table('drivers',
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('fleet_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fleet_id'], ['fleets.fleet_id'], ),
    sa.PrimaryKeyConstraint('driver_id'),
    sa.UniqueConstraint('employee_id'),
    sa.UniqueConstraint('license_number')
    )
    op.create_table('vehicles',
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('fleet_id', sa.UUID(), nullable=False),
    sa.Column('registration_number', sa.String(length=20), nullable=False),
    sa.Column('manufacturer', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('model_year', sa.Integer(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fleet_id'], ['fleets.fleet_id'], ),
    sa.PrimaryKeyConstraint('vehicle_id'),
    sa.UniqueConstraint('registration_number'),
    sa.UniqueConstraint('vin')
    )
    op.create_table('analytics_snapshots',
    sa.Column('snapshot_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('average_fuel_efficiency_kmpl', sa.Float(), nullable=True),
    sa.Column('fuel_trend', sa.String(length=20), nullable=True),
    sa.Column('driver_score', sa.Float(), nullable=True),
    sa.Column('driving_style', sa.String(length=30), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('health_status', sa.String(length=30), nullable=True),
    sa.Column('maintenance_risk', sa.String(length=30), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('insights', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_index(op.f('ix_analytics_snapshots_timestamp'), 'analytics_snapshots', ['timestamp'], unique=False)
    op.create_index(op.f('ix_analytics_snapshots_vehicle_id'), 'analytics_snapshots', ['vehicle_id'], unique=False)
    op.create_table('trips',
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trip_status', sa.String(length=20), nullable=False),
    sa.Column('start_odometer_km', sa.Float(), nullable=False),
    sa.Column('end_odometer_km', sa.Float(), nullable=False),
    sa.Column('distance_travelled_km', sa.Float(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('average_speed_kmh', sa.Float(), nullable=False),
    sa.Column('maximum_speed_kmh', sa.Float(), nullable=False),
    sa.Column('fuel_consumed_liters', sa.Float(), nullable=False),
    sa.Column('trip_score', sa.Integer(), nullable=False),
    sa.Column('eco_score', sa.Integer(), nullable=False),
    sa.Column('safety_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('trip_id')
    )
    op.create_table('maintenance_events',
    sa.Column('maintenance_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('issue', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.trip_id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('maintenance_id')
    )
    op.create_index(op.f('ix_maintenance_events_vehicle_id'), 'maintenance_events', ['vehicle_id'], unique=False)
    op.create_table('telemetry',
    sa.Column('telemetry_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('speed_kmh', sa.Float(), nullable=False),
    sa.Column('acceleration_mps2', sa.Float(), nullable=False),
    sa.Column('heading_deg', sa.Float(), nullable=False),
    sa.Column('odometer_km', sa.Float(), nullable=False),
    sa.Column('rpm', sa.Integer(), nullable=False),
    sa.Column('engine_load_percent', sa.Float(), nullable=False),
    sa.Column('throttle_position_percent', sa.Float(), nullable=False),
    sa.Column('coolant_temperature_c', sa.Float(), nullable=False),
    sa.Column('oil_temperature_c', sa.Float(), nullable=True),
    sa.Column('oil_pressure_kpa', sa.Float(), nullable=True),
    sa.Column('intake_air_temperature_c', sa.Float(), nullable=True),
    sa.Column('maf_gps', sa.Float(), nullable=True),
    sa.Column('map_kpa', sa.Float(), nullable=True),
    sa.Column('fuel_rate_lph', sa.Float(), nullable=False),
    sa.Column('fuel_level_percent', sa.Float(), nullable=True),
    sa.Column('gear', sa.Integer(), nullable=False),
    sa.Column('transmission_temperature_c', sa.Float(), nullable=True),
    sa.Column('accelerator_pedal_percent', sa.Float(), nullable=True),
    sa.Column('brake_pedal_percent', sa.Float(), nullable=True),
    sa.Column('steering_angle_deg', sa.Float(), nullable=True),
    sa.Column('brake_pressure_bar', sa.Float(), nullable=True),
    sa.Column('abs_active', sa.Boolean(), nullable=True),
    sa.Column('battery_voltage_v', sa.Float(), nullable=True),
    sa.Column('alternator_voltage_v', sa.Float(), nullable=True),
    sa.Column('ambient_temperature_c', sa.Float(), nullable=True),
    sa.Column('weather_condition', sa.String(length=30), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('altitude_m', sa.Float(), nullable=True),
    sa.Column('driver_personality', sa.String(length=30), nullable=True),
    sa.Column('road_type', sa.String(length=30), nullable=True),
    sa.Column('traffic_level', sa.String(length=20), nullable=True),
    sa.Column('vehicle_load_percent', sa.Float(), nullable=True),
    sa.Column('trip_phase', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.trip_id'], ),
    sa.PrimaryKeyConstraint('telemetry_id')
    )
    op.create_index(op.f('ix_telemetry_timestamp'), 'telemetry', ['timestamp'], unique=False)
    op.create_index(op.f('ix_telemetry_trip_id'), 'telemetry', ['trip_id'], unique=False)
    op.create_table('alerts',
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('telemetry_id', sa.BigInteger(), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['telemetry_id'], ['telemetry.telemetry_id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.trip_id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_index(op.f('ix_alerts_telemetry_id'), 'alerts', ['telemetry_id'], unique=False)
    op.create_index(op.f('ix_alerts_trip_id'), 'alerts', ['trip_id'], unique=False)
    op.create_index(op.f('ix_alerts_vehicle_id'), 'alerts', ['vehicle_id'], unique=False)
    op.create_table('telemetry_analysis',
    sa.Column('analysis_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('telemetry_id', sa.BigInteger(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fuel_efficiency_kmpl', sa.Float(), nullable=True),
    sa.Column('fuel_rating', sa.String(length=20), nullable=True),
    sa.Column('harsh_acceleration', sa.Boolean(), nullable=False),
    sa.Column('harsh_braking', sa.Boolean(), nullable=False),
    sa.Column('overspeeding', sa.Boolean(), nullable=False),
    sa.Column('driver_score', sa.Float(), nullable=True),
    sa.Column('engine_stress_score', sa.Float(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('health_status', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['telemetry_id'], ['telemetry.telemetry_id'], ),
    sa.PrimaryKeyConstraint('analysis_id')
    )
    op.create_index(op.f('ix_telemetry_analysis_analyzed_at'), 'telemetry_analysis', ['analyzed_at'], unique=False)
    op.create_index(op.f('ix_telemetry_analysis_telemetry_id'), 'telemetry_analysis', ['telemetry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_analysis_telemetry_id'), table_name='telemetry_analysis')
    op.drop_index(op.f('ix_telemetry_analysis_analyzed_at'), table_name='telemetry_analysis')
    op.drop_table('telemetry_analysis')
    op.drop_index(op.f('ix_alerts_vehicle_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_trip_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_telemetry_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_telemetry_trip_id'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_timestamp'), table_name='telemetry')
    op.drop_table('telemetry')
    op.drop_index(op.f('ix_maintenance_events_vehicle_id'), table_name='maintenance_events')
    op.drop_table('maintenance_events')
    op.drop_table('trips')
    op.drop_index(op.f('ix_analytics_snapshots_vehicle_id'), table_name='analytics_snapshots')
    op.drop_index(op.f('ix_analytics_snapshots_timestamp'), table_name='analytics_snapshots')
    op.drop_table('analytics_snapshots')
    op.drop_table('vehicles')
    op.drop_table('drivers')
    op.drop_table('fleets')
    # ### end Alembic commands ###
